services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: how_to_tech_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: howtotech
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: how_to_tech_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@howtotech.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
