services:
  - type: web
    name: howtotech-api
    runtime: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: BACKEND_CORS_ORIGINS
        value: "https://httv1-jcbm4auco-mukheshvadlamudis-projects.vercel.app,https://httv1.vercel.app,http://localhost:3000"
